<div>
    <div>
        <x-jet-form-section submit="addToken">
            <x-slot name="title">
                {{ __('YouTube OAuth Tokens') }}
            </x-slot>

            <x-slot name="description">
                <p class="text-xl">Add YouTube OAuth Token info, generated by the PureDev Labs "youtube-oauth" script, to the pool of available tokens.</p>
            </x-slot>

            <x-slot name="form">
                <div class="col-span-6 sm:col-span-6">
                    <x-jet-label for="accessToken" value="{{ __('Access Token') }}" />
                    <x-jet-input id="accessToken" type="text" class="mt-1 block w-full" wire:model.defer="state.accessToken" />
                    @error('state.accessToken') <span class="block font-medium text-sm mt-2" style="color:red">This is a required field.</span> @enderror
                </div>
                <div class="col-span-6 sm:col-span-6">
                    <x-jet-label for="refreshToken" value="{{ __('Refresh Token') }}" />
                    <x-jet-input id="refreshToken" type="text" class="mt-1 block w-full" wire:model.defer="state.refreshToken" />
                    @error('state.refreshToken') <span class="block font-medium text-sm mt-2" style="color:red">This is a required field.</span> @enderror
                </div>
                <div class="col-span-6 sm:col-span-6">
                    <x-jet-label for="expiryTime" value="{{ __('Seconds to Expiration') }}" />
                    <x-jet-input id="expiryTime" type="text" class="mt-1 block w-full" wire:model.defer="state.expiryTime" />
                    @error('state.expiryTime') <span class="block font-medium text-sm mt-2" style="color:red">This is a required field and value must be numeric.</span> @enderror
                </div>
            </x-slot>

            <x-slot name="actions">
                <x-jet-action-message class="mr-3" on="saved">
                    {{ __('Saved.') }}
                </x-jet-action-message>

                <x-jet-button wire:loading.attr="disabled">
                    {{ __('Save') }}
                </x-jet-button>
            </x-slot>
        </x-jet-form-section>

        <x-jet-section-border />

        <div class="flex flex-col">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Access Token
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Refresh Token
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Expires On
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Last Refresh
                                    </th>
                                    <th scope="col" class="relative px-6 py-3 text-right">
                                        Action&nbsp;&nbsp;&nbsp;&nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="bg-white divide-y divide-gray-200">
                                @foreach ($data as $item)
                                    <tr{!! ((int)$item->expiry_time < time()) ? " style='background-color:#ffe7e6'" : "" !!}>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="flex items-center">
                                                <div class="ml-4">
                                                    <div class="text-sm font-medium text-gray-900" title="{{ $item->access_token }}">
                                                        {{ (strlen($item->access_token) > 30) ? substr($item->access_token, 0, 30) . "..." : $item->access_token }}
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="text-sm text-gray-900" title="{{ $item->refresh_token }}">
                                                {{ (strlen($item->refresh_token) > 30) ? substr($item->refresh_token, 0, 30) . "..." : $item->refresh_token }}
                                            </div>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="text-sm text-gray-900">
                                                {{ date('Y-m-d H:i:s', (int)$item->expiry_time) }}
                                                @if ((int)$item->expiry_time < time())
                                                    <span style="color:red"><sup><b>EXPIRED!</b></sup></span>
                                                @endif
                                            </div>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap">
                                            <div class="text-sm text-gray-900"> {{ date('Y-m-d H:i:s', strtotime($item->updated_at)) }}</div>
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <x-jet-danger-button wire:click="deleteToken({{ $item->id }})" onclick="confirm('Are you sure you want to remove this Token?') || event.stopImmediatePropagation()">
                                                {{ __('Delete') }}
                                            </x-jet-button>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
